UI/Web/Models/UserManager/SearchUserModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Web.Models.UserManager
{
    public class SearchUserModel
    {
        public string SearchKeyword { get; set; }
    }
}

UI/Web/Models/UserManager/UserModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Web.Models.UserManager
{

    public class UserCreateModel
    {
        /// <summary>
        /// 
        /// </summary>
        [Required]
        [Display(Name = "User name")]
        public string Username { get; set; }


        [Required]
        [Display(Name = "Email")]
        public string Email { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public string PhoneNumber { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public string FirstName { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public string LastName { get; set; }


        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class UserModel : BaseNoisEntityModel
    {
        /// <summary>
        /// 
        /// </summary>
        public string UserId { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [Required]
        [Display(Name = "User name")]
        public string Username { get; set; }
        
        /// <summary>
        /// 
        /// </summary>
        public string Email { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public string PhoneNumber { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public string FirstName { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public string LastName { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public bool IsActive { get; set; }
    }


}

UI/Web/Models/UserManager/UserRoleModel.cs
using FluentValidation.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Web.Validators;

namespace Web.Models.UserManager
{
    [Validator(typeof(UserRoleValidator))]
    public class UserRoleModel : BaseNoisEntityModel
    {
        /// <summary>
        /// get or set name
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// get or set is system name or not
        /// </summary>
        public bool IsSystem { get; set; }
        /// <summary>
        /// get or set is active or not
        /// </summary>
        public bool IsActive { get; set; }
    }
}

UI/Web/Models/UserManager/User_Model.cs
using FluentValidation;
using FluentValidation.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Web.Models.Common;

namespace Web.Models.UserManager
{
    [Validator(typeof(User_ModelValidator))]
    public class User_Model : BaseNoisEntityModel
    {
        public int UserId { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string PhoneNumber { get; set; }
        public bool Active { get; set; }
        //public UserRoleViewModel Role { get; set; }
        public List<UserRoleViewModel> Roles { get; set; }
        public string ResetPassword { get; set; }
        public List<DepartmentViewModel> Departments { get; set; }
        public User_Model()
        {
            Roles = new List<UserRoleViewModel>();
        }
    }

    public class User_ModelValidator : AbstractValidator<User_Model>
    {
        public User_ModelValidator()
        {
            RuleFor(x => x.UserName).NotEmpty().WithMessage("Username is required");
            RuleFor(x => x.Password).NotEmpty().WithMessage("Password id required");
            RuleFor(x => x.Password).Length(6, int.MaxValue).WithMessage("Password least 6 characters");
            RuleFor(x => x.ConfirmPassword).NotEmpty().WithMessage("Confirm Password id required");
            RuleFor(x => x.ConfirmPassword).Length(6, 16).WithMessage("Confirm Password least 6 characters");
            RuleFor(x => x.Password).Equal(u => u.ConfirmPassword).WithMessage("Password and ConfirmPassword not match");
            RuleFor(x => x.Email).EmailAddress().WithMessage("Invalid Email");
        }
    }

    public class UserRoleViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public UserRoleViewModel()
        {
            Id = 0;
            Name = "";
        }
    }
}

UI/Web/Controllers/UserManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Service.Implement;
using Service.Interface;
using Service.Security;
using Service.Users;
using Web.Extend;
using Web.Models;
using Web.Models.UserManager;
using Entities.Domain.Users;
using Web.Models.Common;
using Service.Departments;
using Web.Models.Department;
using Nois.Web.Framework.Kendoui;
using System.IO;

namespace Web.Controllers
{
    [Authorize]
    public class UserManagerController : BaseController
    {
        private readonly IUserService _userService;
        private readonly IUserRoleService _userRoleService;
        private readonly IPermissionService _permissionService;
        private readonly IUserRegistrationService _userRegistrationService;
        private readonly IEncryptionService _encryptionService;
        private readonly IDepartmentService _departmentService;

        public UserManagerController(IUserService userService,
            IUserRoleService userRoleService,
            IPermissionService permissionService,
            IUserRegistrationService userRegistrationService,
            IEncryptionService encryptionService,
            IDepartmentService departmentService
            )
        {
            _userService = userService;
            _userRoleService = userRoleService;
            _permissionService = permissionService;
            _userRegistrationService = userRegistrationService;
            _encryptionService = encryptionService;
            _departmentService = departmentService;
        }

        //get all userrole for usermanager
        [HttpPost]
        public JsonResult GetAllUserRole(DataSourceRequest command)
        {
            var userRoles = _userService.GetAllUserRolesAsync();
            var data = userRoles.Result.Where(u => u.SystemName != SystemUserRoleNames.MeetingLeaders && u.SystemName != SystemUserRoleNames.Guest)
                                        .Select(x => new UserRoleViewModel
            {
                Id = x.Id,
                Name = x.Name
            });
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> Index()
        {
            if (await _permissionService.Authorize(PermissionProvider.ManageUser, User.Identity.Name))
                return View("List");

            return View("List");
        }

        [HttpPost]
        public ActionResult List(DataSourceRequest command, SearchUserModel model)
        {
            var users = _userService.GetAllUsersAsync(searchKeyword: model.SearchKeyword, pageIndex:command.Page-1, pageSize:command.PageSize);

            var gridModel = new DataSourceResult
            {
                Data = users.Select(u => new User_Model
                {
                    Id = u.Id,
                    Email = u.Email,
                    FirstName = u.FirstName,
                    LastName = u.LastName,
                    PhoneNumber = u.PhoneNumber,
                    UserName = u.Username,
                    Active = u.Active,
                    //Role = GetUserRoleForViewModel(u.UserRoles),
                    Roles = u.UserRoles.Select( ur => new UserRoleViewModel() { Id = ur.Id, Name = ur.Name }).ToList(),
                    ResetPassword = "",
                    Departments = u.Departments.Select(ud=> new DepartmentViewModel() { Id = ud.Id, Name = ud.Name }).ToList()
                }),
                Total = users.TotalCount
            };

            // Return the result as JSON
            return Json(gridModel);
        }
        
        [HttpPost]
        public async Task<ActionResult> Create(User_Model model)
        {
            if (ModelState.IsValid)
            {
                var user = new User()
                {
                    UserGuid = Guid.NewGuid(),
                    Username = model.UserName,
                    Email = model.Email,
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    PhoneNumber = model.PhoneNumber,
                    Active = model.Active,
                    //DepartmentId = model.Roles.Any(r => r.Name ==  "Administrators") ? 0 : model.Department.Id
                };

                foreach (var department in model.Departments)
                {
                    var d = _departmentService.GetByIdAsync(department.Id).Result;
                    user.Departments.Add(d);
                }

                foreach (var role in model.Roles)
                {
                    var userRole = _userService.GetUserRoleByIdAsync(role.Id);
                    user.UserRoles.Add(userRole);
                }          

                var result = await _userRegistrationService.RegisterUser(new UserRegistrationRequest(user, model.Email, model.UserName, model.Password));
                if(!result.Success)
                {
                    return Content(string.Join(", ", result.Errors));
                }
                else
                    return Json(new{ status = "success" });
            }

            // If we got this far, something failed, redisplay form
            return Json(new { Data = new[] { model } });
            //return View(model);
        }
        
        [HttpPost]
        public async Task<ActionResult> Update(User_Model model)
        {
            var listError = new List<string>();
            //if (ModelState.IsValid)
            {

                var existUser = await _userService.GetUserByUsernameAsync(model.UserName);
                if (existUser == null)
                    listError.Add("Not exist user");
                else
                {
                    var existUserByEmail = await _userService.GetUserByEmailAsync(model.Email);
                    if (existUserByEmail != null)
                    {
                        if (existUserByEmail.Username == model.UserName)
                        {
                            existUserByEmail.FirstName = model.FirstName;
                            existUserByEmail.LastName = model.LastName;
                            existUserByEmail.Active = model.Active;
                            existUserByEmail.PhoneNumber = model.PhoneNumber;

                            //User departments
                            if (model.Departments != null && model.Departments.Count() > 0)
                            {
                                foreach (var department in existUserByEmail.Departments.ToList())
                                {
                                    existUserByEmail.Departments.Remove(department);
                                }

                                var addedDepartments = await _departmentService.GetDepartmentByIdsAsync(model.Departments.Select(d => d.Id).ToList());//  _userRoleService.GetUserRolesByIdsAsync(model.Roles.Where(mr => existUserByEmail.UserRoles.All(r => r.Id != mr.Id)).Select(mr => mr.Id).ToList());

                                foreach (var department in addedDepartments.ToList())
                                {
                                    existUserByEmail.Departments.Add(department);
                                }
                            }
                            if (!string.IsNullOrEmpty(model.ResetPassword))
                            {
                                string saltKey = _encryptionService.CreateSaltKey(5);
                                existUserByEmail.PasswordSalt = saltKey;
                                existUserByEmail.Password = _encryptionService.CreatePasswordHash(model.ResetPassword, saltKey);
                            }

                            //User roles
                            foreach (var role in existUserByEmail.UserRoles.Where(r=>r.SystemName!=SystemUserRoleNames.MeetingLeaders && model.Roles.All(mr=>mr.Id!=r.Id)).ToList())
                            {
                                existUserByEmail.UserRoles.Remove(role);
                            }

                            var addedRoles = await _userRoleService.GetUserRolesByIdsAsync(model.Roles.Where(mr => existUserByEmail.UserRoles.All(r => r.Id != mr.Id)).Select(mr => mr.Id).ToList());

                            foreach (var role in addedRoles)
                            {
                                existUserByEmail.UserRoles.Add(role);
                            }
                            await _userService.UpdateUserAsync(existUserByEmail);


                            return Json(new
                            {
                                status = "success",
                            });
                        }
                        else
                        {
                            listError.Add("This email is belong to another user");
                        }
                    }
                    else
                    {
                        existUser.Email = model.Email;
                        existUser.FirstName = model.FirstName;
                        existUser.LastName = model.LastName;
                        existUser.Active = model.Active;
                        existUser.PhoneNumber = model.PhoneNumber;

                        foreach (var department in existUser.Departments.ToList())
                        {
                            existUser.Departments.Remove(department);
                        }

                        var addedDepartments = await _departmentService.GetDepartmentByIdsAsync(model.Departments.Select(d => d.Id).ToList());//  _userRoleService.GetUserRolesByIdsAsync(model.Roles.Where(mr => existUserByEmail.UserRoles.All(r => r.Id != mr.Id)).Select(mr => mr.Id).ToList());

                        foreach (var department in addedDepartments.ToList())
                        {
                            existUser.Departments.Add(department);
                        }

UI/Web/Views/UserManager/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_KendoUILayout.cshtml";
}
@model Web.Models.UserManager.UserCreateModel

<div class="row">

    <div class="col-md-12 ">
        <!-- BASIC -->
        <div class="box border green">
            <div class="box-title">
                <h4><i class="fa fa-bars"></i>Create</h4>
            </div>
            <div class="box-body big">
                <h3 class="form-title">Create a new account.</h3>

                @using (Html.BeginForm("Create", "UserManager", FormMethod.Post, new { @role = "form", @class = "form-horizontal" }))
                {
                    @Html.AntiForgeryToken()

                    @Html.ValidationSummary()
                    <div class="form-group">
                        @Html.LabelFor(m => m.Username, new { @class = "col-md-4 control-label" })
                        <div class="col-md-8">
                            @Html.TextBoxFor(m => m.Username, new { @class = "form-control", @id = "exampleInputEmail1", @placeholder = "Username" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Password, new { @class = "col-md-4 control-label" })
                        <div class="col-md-8">
                            @Html.PasswordFor(m => m.Password, new { @class = "form-control", @placeholder = "Password" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-4 control-label" })
                        <div class="col-md-8">
                            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control", @placeholder = "Password Confirm" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(m => m.Email, new { @class = "col-md-4 control-label" })
                        <div class="col-md-8">
                            @Html.TextBoxFor(m => m.Email, new { @class = "form-control", @placeholder = "Email" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.FirstName, new { @class = "col-md-4 control-label" })
                        <div class="col-md-8">
                            @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control", @placeholder = "FirstName" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.LastName, new { @class = "col-md-4 control-label" })
                        <div class="col-md-8">
                            @Html.TextBoxFor(m => m.LastName, new { @class = "form-control", @placeholder = "LastName" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(m => m.PhoneNumber, new { @class = "col-md-4 control-label" })
                        <div class="col-md-8">
                            @Html.TextBoxFor(m => m.PhoneNumber, new { @class = "form-control", @placeholder = "Phone Number" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-5">
                            <button type="submit" class="btn btn-success  pull-right">Create</button>
                        </div>
                        <div class="  col-md-1 ">
                            <button onclick="window.location='@Url.Action("Index", "UserManager")'" class=" btn btn-success pull-right">Cancel</button>
                        </div>
                    </div>
                }
            </div>
        </div>
        <!-- /BASIC -->

    </div>
</div>
@section bottomjs{
    <script>
        $(document).ready(function () {
            $("#nav-dashboard").addClass("active")
        });
    </script>

}
@Scripts.Render("~/bundles/jqueryval")

UI/Web/Views/UserManager/Edit.cshtml
@using Web.Models;
@model ManageModel

@{
    ViewBag.Title = "User Profile";
    Layout = "~/Views/Shared/_KendoUILayout.cshtml";
}

<!-- USER PROFILE -->
<div class="row">
    <div class="col-md-12">
        <!-- BOX -->
        <div class="form-group">
            
            <div class=" pull-left " style="margin-bottom: 10px">
                <button onclick="window.location='@Url.Action("Index", "UserManager")'" class=" btn btn-success pull-right">Back to list</button>
            </div>
        </div>
        <div class="box border blue">
            <div class="box-title">
                <h4><i class="fa fa-user"></i><span class="hidden-inline-mobile"> </span></h4>
            </div>

            <div class="box-body">
                <div class="tabbable header-tabs user-profile">
                    <ul class="nav nav-tabs">
                        <li><a href="#pro_help" data-toggle="tab"><i class="fa fa-question"></i> <span class="hidden-inline-mobile"> Other</span></a></li>
                        <li><a href="#pro_edit" data-toggle="tab"><i class="fa fa-edit"></i> <span class="hidden-inline-mobile"> Edit Password</span></a></li>
                        <li class="active"><a href="#pro_overview" data-toggle="tab"><i class="fa fa-dot-circle-o"></i> <span class="hidden-inline-mobile">Overview</span></a></li>
                    </ul>
                    <div class="tab-content">
                        <!-- OVERVIEW -->
                        <div class="tab-pane fade in active" id="pro_overview">
                            
                            @Html.Partial("_ChangeInfoPartial",Model.InfoModel)

                            
                        </div>
                        <!-- /OVERVIEW -->
                        <!-- EDIT ACCOUNT -->
                        <div class="tab-pane fade" id="pro_edit">

                            @Html.Partial("_ChangePasswordPartial",Model.ResetPasswordModel)

                        </div>
                        <!-- /EDIT ACCOUNT -->
                        <!-- HELP -->
                        <div class="tab-pane fade" id="pro_help">

                            @Html.Partial("_ChangeRole", Model.RoleModel)
                        </div>
                        <!-- /HELP -->
                    </div>
                </div>
                <!-- /USER PROFILE -->





            </div>
        </div>
    </div>
</div>
@section bottomjs
{
  
 }

UI/Web/Views/UserManager/Index.cshtml
@{
    ViewBag.Title = "Manage User";
    Layout = "~/Views/Shared/_KendoUILayout.cshtml";
}

<div class="form-group">
    <a href="@Url.Action("Create")" class="btn btn-info btn-info-custom" title="Add New User"><i class="fa fa-plus"></i>Add New User</a>
    <div class="pull-right col-xs-4"  style="padding-right:0">
        <input type="text" id="SearchKeyword" placeholder="Search" class="form-control" />
    </div>
</div>

<div class="form-group">
    <div id="grid"></div>
    <input type="submit" id="btnRefresh" name="btnRefresh" style="display: none" />

</div>


@section bottomjs
{

    <script src="@Url.Content("~/Scripts/kendo/2014.1.318/kendo.web.min.js")"></script>
    <script>
        $(document).ready(function () {

            var datasource = new kendo.data.DataSource({
                type: "json",
                transport: {
                    read: {
                        url: "@Html.Raw(Url.Action("List", "UserManager"))",
                        type: "POST",
                        dataType: "json",
                        data: additionalData
                    },
                    destroy: {
                        url: "@Html.Raw(Url.Action("Delete", "UserManager"))",
                        type: "POST",
                        dataType: "json"
                    },
                    create: {
                        url: "@Html.Raw(Url.Action("Create", "UserManager"))",
                        type: "POST",
                        dataType: "json"
                    },
                    update: {
                        url: "@Html.Raw(Url.Action("Update", "UserManager"))",
                        type: "POST",
                        dataType: "json"
                    }

                },
                schema: {
                    data: "Data",
                    total: "Total",
                    errors: "Errors",
                    model: {
                        id: "Id",
                        fields: {
                            Username: { editable: true },
                            Email: { editable: true },
                            FirstName: { editable: true },
                            LastName: { editable: true },
                            IsActive: { editable: true, type:"boolean" },
                        }
                    }
                },
                requestEnd: function (e) {
                    if (e.type == "create" || e.type == "update") {
                        this.read();
                    }
                },
                error: function (e) {
                    display_kendoui_grid_error(e);
                    // Cancel the changes
                    this.cancelChanges();
                },
                pageSize: 6,
                serverPaging: true,
                serverFiltering: true,
                serverSorting: true
            });


            $("#grid").kendoGrid({
                dataSource: datasource,
                pageable: {
                    refresh: true,
                },
                height: 'auto',
                //toolbar: ["create"],
                edit: function (e) {
                 
                    if (!e.model.isNew()) {
                        console.log(e);
                        $('input[name="Username"]').attr("readonly", true);
                        //little hack here
                        //pre-select the first value of kendoui dropdownlist datasource
                        //for some reasons (maybe, bug) it always sends 0
                        //if no value has been selected (changed) in the dropdownlist
                        //if (allProductAttributes.length > 0) {
                        //    e.model.ProductAttributeId = allProductAttributes[0].Id;
                        //}
                        //if (allAttributeControlMeasureTypes.length > 0) {
                        //    e.model.AttributeControlMeasureTypeId = allAttributeControlMeasureTypes[0].Id;
                        //}
                    }
                },
                editable: {
                    confirmation: true,
                    mode: "popup"
                },
                scrollable: false,
                columns: [
                    {
                        field: "Username",
                        title: "Username",
                        width: 250,
                        template: '<a href="/UserManager/Edit?userId=#=Id#">#:Username#</a>'
                    },

                    {
                        field: "Email",
                        title: "Email",
                        width: 250,

                        template: "#:Email#"
                    },
                    {
                        field: "FirstName",
                        title: "First Name",
                        width: 250,
                        template: "#:FirstName#"
                    },
                    {
                        field: "LastName",
                        title: "Last Name",
                        width: 250,
                        template: "#:LastName#"
                    },
                    {
                        field: "IsActive",
                        title: "Active ",
                        width: 250,
                        template: "#:IsActive#"
                    },
                    {
                        command: [
                            {
                                name: "edit",
                                text: "",
                                template: "<a class='k-button k-grid-edit' href='' style='min-width:16px;'><span class='k-icon k-edit'></span></a>"
                            },
                            //{
                            //    name: "destroy",
                            //    text: "Delete"
                            //}
                        ],
                        width: 200
                    }
                ]
            });

            //search
            $('#SearchKeyword').bind("input", function (e) {
                if (this.value.length >= 3 || e.keyCode == 13 || e.keyCode == 8 || e.keyCode == 46 || this.value.length == 0) {
                    var grid = $('#grid').data('kendoGrid');
                    grid.dataSource.page(1); //new search. Set page size to 1
                    grid.dataSource.read();

                }
                return false;
            });



        });
        function additionalData() {
            return {
                SearchKeyword: $('#SearchKeyword').val()
            };
        }


        //local datasource
        var allProductAttributes = [

        ];

        var allAttributeControlTypes = [

        ];

        function productAttributeDropDownEditor(container, options) {
            $('<input required data-text-field="Name" data-value-field="Id" data-bind="value:ProductAttributeId"/>')
                .appendTo(container)
                .kendoDropDownList({
                    autoBind: false,
                    dataSource: allProductAttributes
                });
        }

        function attributeControlTypeDropDownEditor(container, options) {
            $('<input required data-text-field="Name" data-value-field="Id" data-bind="value:AttributeControlMeasureTypeId"/>')
                .appendTo(container)
                .kendoDropDownList({
                    autoBind: false,
                    dataSource: allAttributeControlTypes
                });
        }
    </script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#btnRefresh').click(function () {
                //refresh grid
                var grid = $("#grid").data('kendoGrid');
                grid.dataSource.read();

                //return false to don't reload a page
                return false;
            });
        });

       

        function display_kendoui_grid_error(e) {
            if (e.errors) {
                if ((typeof e.errors) == 'string') {
                    //single error
                    //display the message
                    alert(e.errors);
                } else {
                    //array of errors
                    //source: http://docs.kendoui.com/getting-started/using-kendo-with/aspnet-mvc/helpers/grid/faq#how-do-i-display-model-state-errors?
                    var message = "The following errors have occurred:";
                    //create a message containing all errors.
                    $.each(e.errors, function (key, value) {
                        if (value.errors) {
                            message += "\n";
                            message += value.errors.join("\n");
                        }
                    });
                    //display the message
                    alert(message);
                }
            } else {
                alert('Error happened');
            }
        }
    </script>
    <script>
        $(document).ready(function () {
            $("#nav-dashboard").addClass("active");
            $(".dashboard-usermanager").addClass("active");
        });
    </script>
}