UI/Web/Models/Dms/DmsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Web.Models.Common;

namespace Web.Models.Dms
{
    public class DmsModel
    {
        public int Id { get; set; }

        public string DmsCode { get; set; }

        public string Description { get; set; }

        public string Note { get; set; }

        public DepartmentViewModel Department { get; set; }

        public List<string> ListUsername { get; set; }

        public int Order { get; set; }

        public bool Active { get; set; }

        public DmsModel()
        {
            ListUsername = new List<string>();
        }
    }
    public class UserAvailableModel
    {
        public string id { get; set; }
        public string text { get; set; }
    }
}

UI/Web/Controllers/DmsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Entities.Domain;
using Service.Departments;
using Service.Interface;
using Service.Users;
using Web.Models.Dms;
using Web.Models.Common;
using Nois.Web.Framework.Kendoui;

namespace Web.Controllers
{

    //Khang comment [Authorize(Roles = "Admin")]
    public class DmsController : Controller
    {
        private readonly IDmsService _dmsService;
        private readonly IUserService _userService;
        private readonly IDepartmentService _departmentService;

        public DmsController(IDmsService dmsService, 
            IUserService userService,
            IDepartmentService departmentService
            )
        {
            _dmsService = dmsService;
            _userService = userService;
            _departmentService = departmentService;
        }

        public ActionResult Index()
        {
            return View();
        }


        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult GetAllUserAvailable()
        {

            var listUsername = _userService.GetAllUsersAsync(active: true).Select(p => p.Username).ToList();
            var allUserModel = listUsername.ToList().Select(
                p => new UserAvailableModel()
                {
                    id = p,
                    text = p

                }).ToList();

            return Json(allUserModel, JsonRequestBehavior.AllowGet);

        }


        /// <summary>
        /// 
        /// </summary>
        /// <param name="command"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> List(DataSourceRequest command, int? departmentId)
        {
            var departmentDefault = _departmentService.SearchDepartment().FirstOrDefault();

            var allDms = await _dmsService.GetDmsByDepartmentId(departmentId == null ? departmentDefault.Id : departmentId.Value, command.Page - 1, command.PageSize);
            
            var allDmsModel = allDms.Select(
               d => new DmsModel
               {
                   Id = d.Id,
                   DmsCode = d.DmsCode,
                   Description = d.Description,
                   Note = d.Note,
                   Department = new DepartmentViewModel() { Id = d.DepartmentId, Name = d.Department.Name },
                   ListUsername = d.Users.Select(u => u.Username).ToList(),
                   Active = d.Active,
                   Order = d.Order
               }).ToList();

            var gridModel = new DataSourceResult
            {
                Data = allDmsModel,
                Total = allDms.TotalCount
            };
            return Json(gridModel);
        }

        [HttpPost]
        public async Task<ActionResult> Create(DmsModel model, int departmentId)
        {
            if (ModelState.IsValid)
            {
                if (string.IsNullOrEmpty(model.DmsCode))
                    return Content("DmsCode is required!");

                //var existDms = _dmsService.GetDmsByDmsCode(model.DmsCode);
                var existDms = await _dmsService.GetDmsByDmsCodeAndDepartmentId(model.DmsCode, departmentId);
                //check exist Dms
                if (existDms != null)
                    return Content(model.DmsCode + " has Existed in this Department!");

                //if (model.Department.Id < 1)
                //    return Content("Department is required!");

                var dms = new Dms()
                {
                    Description = model.Description,
                    Note = model.Note,
                    CreatedDate = DateTime.Now,
                    UpdatedDate = DateTime.Now,
                    DmsCode = model.DmsCode,
                    DepartmentId = departmentId,
                    Active = model.Active,
                    Order = model.Order
                };
                await _dmsService.InsertAsync(dms);
                await _dmsService.UpdateDmsOwner(dms, model.ListUsername);
                return Json(new { Data = new[] { model } });
            }
            return Content("Can not create Dms because model state is invalid");
        }


        [HttpPost]
        public async Task<ActionResult> Update(DmsModel model)
        {
            if (ModelState.IsValid)
            {
                //if (model.Department.Id < 1)
                //    return Content("Department is required!");

                var dms = await _dmsService.GetByIdAsync(model.Id);
                if (dms == null)
                    throw new ArgumentException("No dms found with the specified id");
                if (model.DmsCode != dms.DmsCode)
                {
                    var existedDms = await _dmsService.GetDmsByDmsCodeAndDepartmentId(model.DmsCode, model.Department.Id);
                    if (existedDms == null)
                        dms.DmsCode = model.DmsCode;
                    else
                        return Content("DmsCode has Existed in this Department");
                }

                dms.Description = model.Description;
                dms.Note = model.Note;
                dms.UpdatedDate = DateTime.Now;
                dms.Active = model.Active;
                dms.Order = model.Order;

                await _dmsService.UpdateDmsOwner(dms, model.ListUsername);
                return Json(new { status = "success" });
            }

            return Content("Can not edit Dms because model state is invalid"); ;
        }

        //[HttpPost]
        //public async Task<ActionResult> Delete(int id)
        //{

        //    var dms = await _dmsService.GetDmsById(id);
        //    if (dms == null)
        //        throw new ArgumentException("No dms found with the specified id");
        //    await _dmsService.DeletaAllUserOfDms(id);
        //    await _dmsService.DeleteAsync(dms);
        //    return new NullJsonResult();
        //}

        [HttpPost]
        public JsonResult GetAllDmsForView(DataSourceRequest command, int? departmentId)
        {
            var departmentDefault = _departmentService.SearchDepartment().FirstOrDefault();
            var departmentIdDefault = departmentId == null ? departmentDefault.Id : departmentId.Value;

            var Dmss = _dmsService.GetAllAsync().Result;
            var data = Dmss.Where(d => d.Active == true && d.DepartmentId == departmentIdDefault).OrderBy(d=>d.Order).Select(x => new
            {
                Id = x.Id,
                Code = x.DmsCode
            });
            return Json(data, JsonRequestBehavior.AllowGet);
        }
    }
}

UI/Web/Views/Dms/Index.cshtml
@using Entities.Domain
@using Service.Users

@{
    ViewBag.Title = "Dms Manager";
    Layout = "~/Views/Shared/_KendoUILayout.cshtml";
}
<script src="@Url.Content("~/Scripts/kendo/2014.1.318/kendo.web.min.js")"></script>

<div class="department-filter">
    <input id="department_cbx" />
    <span style="margin: 5px;">Department:</span>
</div>
<div id="grid"></div>



<script>
    var dataSourceDepartment = new kendo.data.DataSource({
        transport: {
            read: {
                dataType: "json",
                type: "POST",
                url: "@Html.Raw(Url.Action("GetAllDepartment", "Department"))"
            }
        }
    });


    var UserDS = [ @{
                var userService = DependencyResolver.Current.GetService<IUserService>();
            var listUsername =  userService.GetAllUsersAsync().Where(u => u.Active).Select(p=>p.Username).ToList();

        }
    @for (var i = 0; i < listUsername.Count(); i++)
        {
            var username = listUsername[i];
            <text>

             "@(Html.Raw(HttpUtility.JavaScriptStringEncode(username)))"
                    </text>
            if (i != listUsername.Count - 1)
            {
                <text>,</text>
            }
        }];

    function ownerDisplay(data) {
        if (data.ListUsername != "")
            return data.ListUsername.join(', ');
        else return '';
    }

    function ownerEditor(container, options) {
        $("<select multiple='multiple' required data-bind='value:" + options.field + "'/>").appendTo(container).kendoMultiSelect({
            dataSource: options.values,
            suggest: true,
        });
    }


    function DepartmentDropDownEditor(container, options) {
        $('<input required data-text-field="Name" data-value-field="Id" data-bind="value:' + options.field + '"/>')
            .appendTo(container)
            .kendoComboBox({
                autoBind: false,
                dataSource: dataSourceDepartment,
                //template: "<i class=\"fa fa-#=data.Name.toLowerCase()#\"></i> #=data.Name#"
            });
    }


    $(document).ready(function () {

        $("#department_cbx").kendoComboBox({
            dataTextField: "Name",
            dataValueField: "Id",
            dataSource: dataSourceDepartment,
            height: 100,
            index: 1,
            change: function (e) {
                $("#grid").data("kendoGrid").dataSource.read();
            }
            , dataBound: function () {
                combobox.select(0);
                $("#grid").data("kendoGrid").dataSource.read();
            }
        });

        var combobox = $("#department_cbx").data("kendoComboBox");

        function department() {
            return { departmentId: combobox.value() }
        }


        //data post to server when create
        function creationData() {
            return { departmentId: combobox.value() }
        }



        var grid = $("#grid").kendoGrid({
            dataSource: {
                type: "json",
                transport: {
                    read: {
                        url: "@Html.Raw(Url.Action("List", "Dms"))",
                    type: "POST",
                    dataType: "json",
                    data: department

                },
                update: {
                    url: "@Html.Raw(Url.Action("Update", "Dms"))",
                type: "POST",
                dataType: "json",
                data: serialize
            },
            destroy: {
                url: "@Html.Raw(Url.Action("Delete", "Dms"))",
            type: "POST",
            //dataType: "json"
        },
            create: {
            url: "@Html.Raw(Url.Action("Create", "Dms"))",
            type: "POST",
            dataType: "json",
            data: creationData
        //data: serialize
    }
    },
    schema: {
        data: "Data",
        total: "Total",
        errors: "Errors",
        model: {
            id: "Id",
            fields: {
                Id: { editable: false, defaultValue: 0 },
                DmsCode: {
                        editable: true,
                        validation:
                    {
                        required: true
                    }
                },
                Description: {
                        editable: true,
                        validation:
                    {
                        required: true,
                        }
                },
                Note: {
                        editable: true,
                        validation:
                    {
                        required: true,
                        }
                },
                Department: {
                        editable: true,
                        defaultValue: { Id: "0", Name: "--  Choose Department  --" }
                },
                ListUsername: {
                        validation:
                        {
                            required: true,
                        }
                    //validation: {
                    //    required: true,
                    //    productnamevalidation: function (input) {
                    //        console.log(input);
                    //        if (input.is("[name='ListUsername']") && input.val() == "") {
                    //            input.attr("data-productnamevalidation-msg", "Product Name should start with capital letter");
                    //            return false;
                    //        }

                    //        return true;
                    //    }
                    //}
                },
                Order: {
                    type: "number"
                },
                Active: {
                        type: "boolean"
                },
                    }
        }
    },
    error: function (e) {
        display_kendoui_grid_error(e);
        //this.cancelChanges();
    },
    requestEnd: function (e) {
        if (e.type == "create" || e.type == "update") {
            this.read();
        }
    },
    pageSize: 10,
        serverPaging: true,
    serverFiltering: true,
    serverSorting: true
    },
    columns: [
        {
            field: "DmsCode",
            title: "DmsCode",
            width: 250,
            template: '#:DmsCode#'
        },
        {
            field: "Description",
            title: "Description",
            width: 250,

            template: "#:Description#"
        },
        {
            field: "Note",
            title: "Note",
            width: 250,
            template: "#:Note#"
        },
        //{
        //    field: "Department",
        //    title: "Department",
        //    width: 150,
        //    editor: DepartmentDropDownEditor,
        //    template: "#=Department.Name#"
        //},
        {
            field: "ListUsername",
            title: "Owner",
            width: 250,
            template: ownerDisplay,
            editor: ownerEditor,
            values: UserDS,
        },
                    {
                        field: "Order",
                        title: "Order",
                        width: 100,
                        format: "n0",
                        template: "#=Order#"
                    },
                    {
                        field: "Active",
                        title: "Active",
                        width: 100,
                        template: '<img src="@Url.Content("~/Content/img/")active-#=Active#.gif" />'
                    },
        {
            command: [
                {
                    name: "edit",
                    text: "",
                    template: "<a class='k-button k-grid-edit' href='' style='min-width:16px;'><span class='k-icon k-edit'></span></a>"
                }
            ],
            width: 200
        }
    ],
        pageable: {
        refresh: true,
        pageSizes: ["5", "10", "15", "20"]
        },
    editable: "inline",
        toolbar: ["create"],
    edit: editorFunction,
    scrollable: false
        }).data("kendoGrid");


    })



        function editorFunction(e) {
            if (e.model.Id != '') {
                //not allow edit DmsCode
                //e.container.find("input[name=DmsCode]").attr("disabled", "true");
                //e.container.find("input[name=DmsCode]").css("border", "none");
            }
            else//event create button
            {
            }
        }


        function serialize(data) {
            for (var property in data) {
                if ($.isArray(data[property])) {
                    serializeArray(property, data[property], data);
                }
                if (data[property] == null) {
                    data[property] = " ";
                }
            }
        }
        function serializeArray(prefix, array, result) {
            for (var i = 0; i < array.length; i++) {
                if ($.isPlainObject(array[i])) {
                    for (var property in array[i]) {
                        result[prefix + "[" + i + "]." + property] = array[i][property];
                    }
                }
                else {
                    result[prefix + "[" + i + "]"] = array[i];
                }
            }
        }
</script>